# Generated by Django 4.2 on 2023-05-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cashbook", "0002_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrxType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=3)),
            ],
        ),
    ]
