# Generated by Django 4.2 on 2023-05-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cashbook", "0003_trxtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trxtype",
            name="name",
            field=models.CharField(max_length=10),
        ),
    ]
